import colorama
from colorama import Fore, Back, Style
colorama.init(autoreset=True)

#Game Title
def The_Blob_Game_Title ():
    print(f'{Fore.RED}████████╗██╗░░██╗███████╗  ██████╗░██╗░░░░░░█████╗░██████╗░  ░██████╗░░█████╗░███╗░░░███╗███████╗')
    print(f'{Fore.BLUE}╚══██╔══╝██║░░██║██╔════╝  ██╔══██╗██║░░░░░██╔══██╗██╔══██╗  ██╔════╝░██╔══██╗████╗░████║██╔════╝')
    print(f'{Fore.GREEN}░░░██║░░░███████║█████╗░░  ██████╦╝██║░░░░░██║░░██║██████╦╝  ██║░░██╗░███████║██╔████╔██║█████╗░░')
    print(f'{Fore.RED}░░░██║░░░██╔══██║██╔══╝░░  ██╔══██╗██║░░░░░██║░░██║██╔══██╗  ██║░░╚██╗██╔══██║██║╚██╔╝██║██╔══╝░░')
    print(f'{Fore.BLUE}░░░██║░░░██║░░██║███████╗  ██████╦╝███████╗╚█████╔╝██████╦╝  ╚██████╔╝██║░░██║██║░╚═╝░██║███████╗')
    print(f'{Fore.GREEN}░░░╚═╝░░░╚═╝░░╚═╝╚══════╝  ╚═════╝░╚══════╝░╚════╝░╚═════╝░  ░╚═════╝░╚═╝░░╚═╝╚═╝░░░░░╚═╝╚══════╝\n')
    print(f'{Fore.RED}                                         ░░░░░░░░░░                                               ')
    print(f'{Fore.BLUE}                                      ░░░░        ░░░░░░                                          ')
    print(f'{Fore.GREEN}                                    ░░                  ░░                                        ')
    print(f'{Fore.RED}                                  ░░                    ░░░░                                      ') 
    print(f'{Fore.BLUE}                                ░░                      ░░░░░░                                    ') 
    print(f'{Fore.GREEN}                                ░░                        ░░░░                                    ') 
    print(f'{Fore.RED}                              ░░                ░░    ░░  ░░░░░░                                  ') 
    print(f'{Fore.BLUE}                              ░░                ██░░  ██    ░░░░                                  ') 
    print(f'{Fore.GREEN}                              ░░                ██░░  ██    ░░░░                                  ') 
    print(f'{Fore.RED}                              ░░            ░░            ░░░░░░                                  ') 
    print(f'{Fore.BLUE}                              ░░░░░░                      ░░░░░░                                  ') 
    print(f'{Fore.GREEN}                                ░░░░░░                  ░░░░░░                                    ') 
    print(f'{Fore.RED}                                ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░                                    ') 
    print(f'{Fore.BLUE}                                    ░░░░░░░░░░░░░░░░░░░░░░                                        ') 


#fire_blob
def Fire_Blob ():
    print(f'{Fore.RED}           ░░              ░░                         ')
    print(f'{Fore.RED}       ░░                  ░░                         ')
    print(f'{Fore.RED}                            ░░                        ')
    print(f'{Fore.RED}                      ▒▒                              ')
    print(f'{Fore.RED}                    ░░▓▓░░                            ')
    print(f'{Fore.RED}                      ▒▒    ░░                        ')
    print(f'{Fore.RED}                  ░░░░      ░░                        ')
    print(f'{Fore.RED}                ░░▒▒▒▒░░░░░░░░                ░░      ')
    print(f'{Fore.RED}                ░░▒▒▓▓▒▒▒▒▒▒▒▒░░░░                    ')
    print(f'{Fore.RED}                ░░▒▒▓▓▒▒▓▓▓▓▓▓▒▒▒▒░░                  ')
    print(f'{Fore.RED}              ▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒                ')
    print(f'{Fore.RED}            ▒▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░              ')
    print(f'{Fore.RED}            ▒▒▓▓██▒▒▓▓▓▓▓▓▓▓▓▓▓▓██░░▓▓░░              ')
    print(f'{Fore.RED}          ░░▓▓▓▓████▓▓▓▓▓▓▓▓▓▓▓▓████▓▓▓▓░░            ')
    print(f'{Fore.RED}          ░░▓▓▓▓████▓▓▓▓▓▓▓▓▓▓▓▓████▓▓▓▓░░            ')
    print(f'{Fore.RED}          ░░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░            ')
    print(f'{Fore.RED}        ▒▒▓▓▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░▓▓▒▒          ')
    print(f'{Fore.RED}      ▒▒▓▓▓▓▓▓▓▓▓▓▓▓▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒        ')
    print(f'{Fore.RED}        ▒▒▒▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒▒▒          ')
    print(f'{Fore.RED}              ░░░░░░▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░                ')
    print(f'{Fore.RED}                    ░░░░░░░░░░░░                      ')

#water_blob
def Water_Blob ():
    print(f'{Fore.BLUE}                           ▒                       ')
    print(f'{Fore.BLUE}                          ▒▒▒                      ')
    print(f'{Fore.BLUE}                        ▒▒▒▒▒▒                     ')
    print(f'{Fore.BLUE}                      ▒▒▒▒▒▒▒▒▒▒                   ')
    print(f'{Fore.BLUE}                    ▒▒▒▒▒▒▒▒▒▒▒▒▒▒                 ')
    print(f'{Fore.BLUE}                  ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒               ')
    print(f'{Fore.BLUE}                ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒             ')
    print(f'{Fore.BLUE}              ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒           ')
    print(f'{Fore.BLUE}             ▒▒▒▒▒██  ▒▒▒▒▒▒▒▒▒▒██  ▒▒▒▒▒          ')
    print(f'{Fore.BLUE}            ▒▒▒▒▒▒████▒▒▒▒▒▒▒▒▒▒████▒▒▒▒▒▒         ')
    print(f'{Fore.BLUE}            ▒▒▒▒▒▒████▒▒▒▒▒▒▒▒▒▒████▒▒▒▒▒▒         ')
    print(f'{Fore.BLUE}            ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒         ')
    print(f'{Fore.BLUE}            ▒▒▒▒▒▒▒▒▒▒████████▒▒▒▒▒▒▒▒▒▒▒▒         ')
    print(f'{Fore.BLUE}            ▒▒▒▒▒▒▒▒▒▒████████▒▒▒▒▒▒▒▒▒▒▒▒         ')
    print(f'{Fore.BLUE}              ▒▒▒▒▒▒▒▒▒▒████▒▒▒▒▒▒▒▒▒▒▒▒           ')
    print(f'{Fore.BLUE}                ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒             ')
    print(f'{Fore.BLUE}                    ▒▒▒▒▒▒▒▒▒▒▒▒▒▒                 ')

#grass_blob
def Grass_Blob():
    print(f'{Fore.GREEN}                              ▒                      ')
    print(f'{Fore.GREEN}                             ▒▒▒                     ')
    print(f'{Fore.GREEN}                            ▒ ▒ ▒                    ')
    print(f'{Fore.GREEN}                           ▒  ▒  ▒                   ')
    print(f'{Fore.GREEN}                          ▒  ▒  ▒                    ')
    print(f'{Fore.GREEN}                         ▒  ▒  ▒                     ')
    print(f'{Fore.GREEN}                          ▒ ▒ ▒                      ')
    print(f'{Fore.GREEN}                           ▒▒▒                       ')
    print(f'{Fore.GREEN}                        ▒▒▒▒▒▒▒                      ')
    print(f'{Fore.GREEN}                   ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒                  ')
    print(f'{Fore.GREEN}                ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒               ')
    print(f'{Fore.GREEN}              ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒             ')
    print(f'{Fore.GREEN}             ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒            ')
    print(f'{Fore.GREEN}            ▒▒▒▒▒▒██  ▒▒▒▒▒▒▒▒▒▒██  ▒▒▒▒▒▒           ')
    print(f'{Fore.GREEN}            ▒▒▒▒▒▒████▒▒▒▒▒▒▒▒▒▒████▒▒▒▒▒▒           ')
    print(f'{Fore.GREEN}            ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒           ')
    print(f'{Fore.GREEN}            ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒           ')
    print(f'{Fore.GREEN}            ▒▒▒▒▒▒▒▒▒▒▒▒      ▒▒▒▒▒▒▒▒▒▒▒            ')
    print(f'{Fore.GREEN}              ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒              ')
    print(f'{Fore.GREEN}                ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒               ')
    print(f'{Fore.GREEN}                    ▒▒▒▒▒▒▒▒▒▒▒▒▒▒                   ')
